- set_fact:
        java_heap_size: "{{ es_ram_limit | regex_search('^\\d+') | int  // 2 }}"
  when: java_heap_size is not defined

- name: Create (or update) ElasticSearch configurations
  k8s:
    state: present
    definition: "{{ lookup('template', 'elasticsearch_configmaps.yaml') }}"
  register: elasticsearch_configmap

- block:
    - name: Get ElasticSearch pods from project
      k8s_facts:
        api_version: v1
        kind: Pod
        namespace: "{{ project_name }}"
      register: all_pods

    - name: Killing  ElasticSearch  pod for apply new configuration
      k8s:
        api_version: v1
        state: absent
        kind: Pod
        name: "{{ item.metadata.name }}"
        namespace: "{{ project_name }}"
      loop: "{{ all_pods.resources }}"
      when:  item.metadata.name | regex_search('es')  == 'es'

  when: elasticsearch_configmap.changed

- name: Create (or update) ElasticSearch deployments
  k8s:
    state: present
    definition: "{{ item }}"
  loop: "{{ lookup('template', 'elasticsearch_deployment.yaml') | from_yaml_all | list }}"

