apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  name: logs-master
rules:
#Add custom blocks to view role
  - apiGroups:
      - ""
    attributeRestrictions: null
    resources:
      - pods/exec
      - pods/portforward

    verbs:
      - create

##########################################
  - apiGroups:
      - ""
    attributeRestrictions: null
    resources:
      - configmaps
      - endpoints
      - persistentvolumeclaims
      - pods
      - replicationcontrollers
      - replicationcontrollers/scale
      - serviceaccounts
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    attributeRestrictions: null
    resources:
      - bindings
      - events
      - limitranges
      - namespaces/status
      - pods/log
      - pods/status
      - replicationcontrollers/status
      - resourcequotas
      - resourcequotas/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    attributeRestrictions: null
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    attributeRestrictions: null
    resources:
      - daemonsets
      - deployments
      - deployments/scale
      - replicasets
      - replicasets/scale
      - statefulsets
      - statefulsets/scale
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    attributeRestrictions: null
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    attributeRestrictions: null
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    attributeRestrictions: null
    resources:
      - daemonsets
      - deployments
      - deployments/scale
      - ingresses
      - networkpolicies
      - replicasets
      - replicasets/scale
      - replicationcontrollers/scale
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy
    attributeRestrictions: null
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    attributeRestrictions: null
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - build.openshift.io
    attributeRestrictions: null
    resources:
      - buildconfigs
      - buildconfigs/webhooks
      - builds
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - build.openshift.io
    attributeRestrictions: null
    resources:
      - builds/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - build.openshift.io
    attributeRestrictions: null
    resources:
      - jenkins
    verbs:
      - view
  - apiGroups:
      - ""
      - apps.openshift.io
    attributeRestrictions: null
    resources:
      - deploymentconfigs
      - deploymentconfigs/scale
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - apps.openshift.io
    attributeRestrictions: null
    resources:
      - deploymentconfigs/log
      - deploymentconfigs/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - image.openshift.io
    attributeRestrictions: null
    resources:
      - imagestreamimages
      - imagestreammappings
      - imagestreams
      - imagestreamtags
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - image.openshift.io
    attributeRestrictions: null
    resources:
      - imagestreams/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - project.openshift.io
    attributeRestrictions: null
    resources:
      - projects
    verbs:
      - get
  - apiGroups:
      - ""
      - quota.openshift.io
    attributeRestrictions: null
    resources:
      - appliedclusterresourcequotas
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - route.openshift.io
    attributeRestrictions: null
    resources:
      - routes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - route.openshift.io
    attributeRestrictions: null
    resources:
      - routes/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - template.openshift.io
    attributeRestrictions: null
    resources:
      - processedtemplates
      - templateconfigs
      - templateinstances
      - templates
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
      - build.openshift.io
    attributeRestrictions: null
    resources:
      - buildlogs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    attributeRestrictions: null
    resources:
      - resourcequotausages
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - servicecatalog.k8s.io
    attributeRestrictions: null
    resources:
      - servicebindings
      - serviceinstances
    verbs:
      - get
      - list
      - watch
