{% if logs_masters | length !=0 %}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: logs-masters
  namespace: "{{ project_name }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logs-master
subjects:
{% for user in logs_masters %}
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: "{{ user }}"
{% endfor %}
{% endif %}
